### ISSUE TITLE
Support for FuseSoC at SoC level

### ISSUE THREAD

**Issue by zeeshanrafique23** [merledu/azadi-new#27]
We have support of [FuseSoC](https://github.com/olofk/fusesoc) at core level and we want to extend it on SoC level.

**Comment by zeeshanrafique23** [comment]
Thanks to @Nameer-Iqbal-Ansari, the support for FuseSoC is added at SoC level.

**Comment by Nameer-Iqbal-Ansari** [comment]
It's been a pleasure working on AZADI.
