### ISSUE TITLE
Ibex config not generating.

### ISSUE THREAD

**Issue by za1nrkhan** [merledu/azadi-new#7]
I get an error while running the UVM environment that depends upon a generated Makefile simulator `-defparam` and 
`-define` options.
Failure to process configuration from ibex_configs.yaml Config experimental-floating-point has differing parameters RVF.
Better remove the RVF parameter from config file as it is read by `ibex_config.py`and each parameter is looked up in the dictionary.

PS. The RVF parameter is enabled by default anyways so no need to explicitly enable it in the config.

**Comment by zeeshanrafique23** [comment]
Okay please fix it and send PR.
